# print('Hello')
# a = input()
# print(a)
# c = input()
# type(c)
# y = int(9.9)
# print(y)
# float(9)
# type(float(9))
# str(0.12)
# type(str(0.12))
# len("Hello world")

print("Hello there! What is your name?")
Name = input()
print('Nice to meet you', Name)
age = input()
birth_year = 2018-int(age)
answer = str(birth_year)
print('You were born in '+answer)